/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author osman
 */
public class Contacto_Consultar extends javax.swing.JPanel {

    

    //Contacto listar, añadir
    
    public Contacto_Consultar() {
        
        
        initComponents();

        
    }

    public Connection conexionmysql() {
        Connection conectar = null;
        try {
            Class.forName("org.gjt.mm.mysql.Driver");
            conectar = DriverManager.getConnection("jdbc:mysql://localhost/contabilidad", "osman", "armando9812");
            if (conectar != null) {
                System.out.println("Conexion exitosa a esquema base mysql");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexion de la base de datos");
        } catch (ClassNotFoundException ex) {
        }
        return conectar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1242, 698));

        jLabel2.setBackground(new java.awt.Color(142, 68, 173));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 68, 173));
        jLabel2.setText("Consultar Contacto");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Codigo:");

        cod.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        cod.setForeground(new java.awt.Color(102, 102, 102));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Nombre:");

        n.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        n.setForeground(new java.awt.Color(102, 102, 102));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Telefono:");

        t.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        t.setForeground(new java.awt.Color(102, 102, 102));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Correo:");

        c.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        c.setForeground(new java.awt.Color(102, 102, 102));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Tipo:");

        jLabel11.setBackground(new java.awt.Color(142, 68, 173));
        jLabel11.setFont(new java.awt.Font("bold_year", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(142, 68, 173));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Modificar.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jLabel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel11KeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(142, 68, 173));
        jLabel9.setFont(new java.awt.Font("bold_year", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(142, 68, 173));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Buscar.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(142, 68, 173));
        jLabel13.setFont(new java.awt.Font("bold_year", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(142, 68, 173));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Limpiar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        tipo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tipo.setForeground(new java.awt.Color(102, 102, 102));
        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "provedor2", "comprador" }));
        tipo.setBorder(null);
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26)
                            .addComponent(jLabel2)
                            .addComponent(jLabel22))
                        .addGap(274, 874, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addComponent(t, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)))
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel22)
                .addGap(24, 24, 24)
                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel26)
                .addGap(30, 30, 30)
                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
 
            conexion con=new conexion();
            Connection reg =con.getConnection();
            String codi = cod.getText();
            String ti = (String)tipo.getSelectedItem();
            ResultSet rs;
            try {
                PreparedStatement pst=reg.prepareStatement("Select * from "+ti+" where Codigo='"+codi+"'");
                rs = pst.executeQuery();
                if (rs.next()) {
                    n.setText(rs.getString(4));
                    t.setText(rs.getString(6));
                    c.setText(rs.getString(2));
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Contacto_Consultar.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        cod.setEditable(true);
        cod.setText("");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void jLabel11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel11KeyPressed
               
    }//GEN-LAST:event_jLabel11KeyPressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       if(n.getText().isEmpty() || c.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Algunos campos estan vacios");
} else {      
conexion con=new conexion();
        String a,b,e,f,g,h;
        a=n.getText();
       
       
        e=t.getText();
    String codi = cod.getText();
     String ti = (String)tipo.getSelectedItem();
         g= c.getText();
         
        String sql2="UPDATE "+ti+" SET Nombre='"+a+"',Correo='"+g+"',Telefono='"+e+"' WHERE Codigo='"+codi+"' " ;       // TODO add your handling code here:
   
        Connection reg =con.getConnection();
          try{
            PreparedStatement pst=reg.prepareStatement(sql2);
          boolean y= pst.execute();
          if(y==true){
          JOptionPane.showMessageDialog(null,"Registros actualizados");
          }  
        }  catch (SQLException ex) {
            Logger.getLogger(Nomina_Empleado_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Algunos campos con valores numericos tienen datos invalidos");
        }
          catch (NullPointerException ex ) {
             JOptionPane.showMessageDialog(null, "Algunos campos estan vacios");
        }
          }
    }//GEN-LAST:event_jLabel11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField cod;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n;
    private javax.swing.JTextField t;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables
}
