/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author osman
 */
public class NominaP extends javax.swing.JPanel {

    

    //Contacto listar, añadir
    public NominaP() {
        
        try{
            for(UIManager.LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()){
                if("Windows".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(Exception ex){
                    
                    }
        initComponents();
        try {                                   
            String[] titulos = {"Nombre" ,"Apellido" ,"Cargo" ,"Salario basico" ,"Basico" ,"Hora extra" ,"Comisiones" ,"Bonos" ,"Auxilio de transporte" ,"Total devengado","Salud","Pension" ,"Fondo de empleados" ,"Retencion en la fuente" ,"Embargos" ,"Total deducido" ,"Neto a pagar" };
            String[] registros = new String[50];
            
            String sql = "SELECT * FROM nomina";
            DefaultTableModel model = new DefaultTableModel(null, titulos);
            //Conectar cc = new Conectar();
            //Connection conect = cc.conexion();
            conexion con=new conexion();
            Connection cn = con.getConnection();
            Statement st = null;
            try {
                st = (Statement) cn.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(NominaP.class.getName()).log(Level.SEVERE, null, ex);
            }
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("Nombre");
                registros[1] = rs.getString("Apellido");
                registros[2] = rs.getString("Cargo");
                registros[3] = rs.getString("Salar");
                registros[4] = rs.getString("ba");
                registros[5] = rs.getString("hex");
                registros[6] = rs.getString("comisiones");
                registros[7] = rs.getString("bon");
                registros[8] = rs.getString("aux");
                registros[9] = rs.getString("tdd");
                registros[10] = rs.getString("salud");
                registros[11] = rs.getString("pen");
                registros[12] = rs.getString("fon");
                registros[13] = rs.getString("reten");
                registros[14] = rs.getString("emb");
                registros[15] = rs.getString("tde");
                registros[16] = rs.getString("neto");
                
                model.addRow(registros);
            }
            jTaux.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(NominaP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaux = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1242, 698));

        BuscarT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BuscarT.setBorder(null);
        BuscarT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarTKeyPressed(evt);
            }
        });

        jTaux.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jTaux.setForeground(new java.awt.Color(102, 102, 102));
        jTaux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cargo", "Salario basico", "basico", "horas extras", "Comisiones", "bonos", "Auxilio de transporte", "Total devengado", "Salud", "Pension", "Fondo de empleados", "Retencion en la fuente", "Embargos", "Total deducido", "Neto a pagar"
            }
        ));
        jTaux.setFocusable(false);
        jTaux.setGridColor(new java.awt.Color(255, 255, 255));
        jTaux.setRowHeight(26);
        jTaux.setSelectionBackground(new java.awt.Color(39, 174, 96));
        jTaux.setShowHorizontalLines(false);
        jTaux.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTaux);

        jLabel2.setBackground(new java.awt.Color(39, 174, 96));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 174, 96));
        jLabel2.setText("Nomina");

        jSeparator3.setBackground(new java.awt.Color(39, 174, 96));
        jSeparator3.setForeground(new java.awt.Color(39, 174, 96));

        jLabel6.setBackground(new java.awt.Color(39, 174, 96));
        jLabel6.setFont(new java.awt.Font("bold_year", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 174, 96));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Generar.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(39, 174, 96));
        jLabel7.setFont(new java.awt.Font("bold_year", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 174, 96));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Agregar.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(39, 174, 96));
        jLabel8.setFont(new java.awt.Font("bold_year", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 174, 96));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Modificar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search_Productos.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(BuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarTKeyPressed
        try {                                   
            String[] titulos = {"Nombre" ,"Apellido" ,"Cargo" ,"Salario basico" ,"Basico" ,"Hora extra" ,"Comisiones" ,"Bonos" ,"Auxilio de transporte" ,"Total devengado","Salud","Pension" ,"Fondo de empleados" ,"Retencion en la fuente" ,"Embargos" ,"Total deducido" ,"Neto a pagar" };
            String[] registros = new String[50];
            
            String sql = "SELECT * FROM nomina WHERE Cedula LIKE '%" + BuscarT.getText() + "%' "
                    + "OR Nombre LIKE '%" + BuscarT.getText() + "%'";
            DefaultTableModel model = new DefaultTableModel(null, titulos);
            //Conectar cc = new Conectar();
            //Connection conect = cc.conexion();
            conexion con=new conexion();
            Connection cn = con.getConnection();
            Statement st = null;
            try {
                st = (Statement) cn.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(NominaP.class.getName()).log(Level.SEVERE, null, ex);
            }
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("Nombre");
                registros[1] = rs.getString("Apellido");
                registros[2] = rs.getString("Cargo");
                registros[3] = rs.getString("Salar");
                registros[4] = rs.getString("ba");
                registros[5] = rs.getString("hex");
                registros[6] = rs.getString("comisiones");
                registros[7] = rs.getString("bon");
                registros[8] = rs.getString("aux");
                registros[9] = rs.getString("tdd");
                registros[10] = rs.getString("salud");
                registros[11] = rs.getString("pen");
                registros[12] = rs.getString("fon");
                registros[13] = rs.getString("reten");
                registros[14] = rs.getString("emb");
                registros[15] = rs.getString("tde");
                registros[16] = rs.getString("neto");
                
                model.addRow(registros);
            }
            jTaux.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(NominaP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarTKeyPressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        Nomina_Generar a=new Nomina_Generar();
        a.setVisible(true);  

        //CuentasAgregar_1 jFrame = new CuentasAgregar_1();
        //jFrame.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Nomina_Empleado a=new Nomina_Empleado();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Nomina_Empleado_Modificar a=new Nomina_Empleado_Modificar();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTaux;
    // End of variables declaration//GEN-END:variables
}
