/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestor;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Y
 */
public class Nomina_Generar extends javax.swing.JFrame {

    /**
     * Creates new form pag
     */
   
    public Nomina_Generar() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/capas.png")).getImage());
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width, this.getBounds().height,20,20);
        AWTUtilities.setWindowShape(this, forma);
        this.setLocationRelativeTo(null);
        
    }
    int a=0;int nn=0;int dep=0;int basico=0;
  int reten=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ced = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        cr = new javax.swing.JTextField();
        dl = new javax.swing.JTextField();
        dt = new javax.swing.JTextField();
        he = new javax.swing.JTextField();
        ven = new javax.swing.JTextField();
        af = new javax.swing.JTextField();
        re = new javax.swing.JTextField();
        iv = new javax.swing.JTextField();
        nh = new javax.swing.JTextField();
        sp = new javax.swing.JTextField();
        apa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ced.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ced.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Digite cedula:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Buscar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Cargo:");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Dias trabajados:");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Dias laborales:");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Horas extra:");

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ventas:");

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Aportes al fondo:");

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Rentas exentas:");

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Interes de vivienda:");

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Salud Prepagada:");

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Bonos:");

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Aportes afc:");

        n.setEditable(false);
        n.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        n.setForeground(new java.awt.Color(102, 102, 102));

        ap.setEditable(false);
        ap.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ap.setForeground(new java.awt.Color(102, 102, 102));
        ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apActionPerformed(evt);
            }
        });

        cr.setEditable(false);
        cr.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        cr.setForeground(new java.awt.Color(102, 102, 102));

        dl.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        dl.setForeground(new java.awt.Color(102, 102, 102));

        dt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        dt.setForeground(new java.awt.Color(102, 102, 102));
        dt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtActionPerformed(evt);
            }
        });

        he.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        he.setForeground(new java.awt.Color(102, 102, 102));

        ven.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ven.setForeground(new java.awt.Color(102, 102, 102));

        af.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        af.setForeground(new java.awt.Color(102, 102, 102));

        re.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        re.setForeground(new java.awt.Color(102, 102, 102));

        iv.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        iv.setForeground(new java.awt.Color(102, 102, 102));

        nh.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        nh.setForeground(new java.awt.Color(102, 102, 102));

        sp.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        sp.setForeground(new java.awt.Color(102, 102, 102));

        apa.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        apa.setForeground(new java.awt.Color(102, 102, 102));

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Embargos:");

        em.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        em.setForeground(new java.awt.Color(102, 102, 102));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Generar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton_Detalles.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(39, 174, 96));

        jLabel33.setBackground(new java.awt.Color(230, 126, 34));
        jLabel33.setForeground(new java.awt.Color(230, 126, 34));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimizar.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel33))
                .addGap(1, 1, 1))
        );

        jPanel8.setBackground(new java.awt.Color(39, 174, 96));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Generar");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ced, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(he)
                                    .addComponent(ven)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(dl, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dt, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(n)
                                    .addComponent(ap)
                                    .addComponent(cr))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(em)
                            .addComponent(af, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iv)
                            .addComponent(re, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apa)
                            .addComponent(nh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sp, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(af, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apActionPerformed

    private void dtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     dt.setVisible(true);
dl.setVisible(true);he.setVisible(true);ven.setVisible(true);af.setVisible(true);em.setVisible(true);
re.setVisible(true);iv.setVisible(true);sp.setVisible(true);nh.setVisible(true);apa.setVisible(true);
jLabel15.setVisible(true);jLabel14.setVisible(true); 
jLabel13.setVisible(true);jLabel12.setVisible(true);jLabel11.setVisible(true);jLabel16.setVisible(true);
jLabel10.setVisible(true);jLabel9.setVisible(true);jLabel8.setVisible(true);jLabel7.setVisible(true);jLabel6.setVisible(true); 
        conexion con=new conexion();
           Connection reg =con.getConnection();
   ResultSet rs;
        try {
            PreparedStatement pst=reg.prepareStatement("Select * from emp where Cedula="+"'"+Integer.parseInt(ced.getText())+"'");
            rs = pst.executeQuery();
            if (rs.next()) {
                n.setText(rs.getString(1));
                ap.setText(rs.getString(2));
            a= rs.getInt(10);
            nn=rs.getInt(12);
           int b=rs.getInt(4);
            
     if(b==0){
     jLabel9.setVisible(false);
     ven.setVisible(false);
      
     ven.setText(""+0);
     cr.setText("Gerente");
     }
     if(b==1){
         cr.setText("Vendedor");
       jLabel9.setVisible(true);
     ven.setVisible(true);ven.setText(""+0);
     jLabel11.setVisible(false);
     re.setVisible(false);  re.setText(""+0);
     jLabel12.setVisible(false);
     re.setVisible(false);  re.setText(""+0);
     jLabel13.setVisible(false);
     sp.setVisible(false);   sp.setText(""+0);
     jLabel14.setVisible(false);
     nh.setVisible(false); nh.setText(""+0);
     jLabel15.setVisible(false);
     apa.setVisible(false); apa.setText(""+0);
     }
     if(b==3){
         cr.setText("Tecnico");
           jLabel9.setVisible(false);
     ven.setVisible(false);            ven.setText(""+0);
      jLabel11.setVisible(false);
     re.setVisible(false);        re.setText(""+0);
     jLabel12.setVisible(false);
     iv.setVisible(false);        iv.setText(""+0);
     jLabel13.setVisible(false);
     sp.setVisible(false);        sp.setText(""+0);
     jLabel14.setVisible(false);
     nh.setVisible(false);       nh.setText(""+0);
     jLabel15.setVisible(false);
     apa.setVisible(false);      apa.setText(""+0);
     }
   
     }
        } catch (SQLException ex) {
            Logger.getLogger(Nomina_Empleado_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   String sql="INSERT INTO nomina(Cedula, Nombre, Apellido, Cargo, Salar, ba,hex, comisiones, bon,aux, tdd, salud, pen, fon, reten, emb, tde, neto) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        conexion con=new conexion();
           Connection reg =con.getConnection();
   try{
            PreparedStatement pst=reg.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(ced.getText()));
            pst.setString(2, n.getText());
            pst.setString(3, ap.getText());
            
            pst.setString(4, cr.getText());
            
            pst.setInt(5,a);
            if(Integer.parseInt(dl.getText())==Integer.parseInt(dt.getText())){
            basico=a;
            }else{
            double b1=a/Integer.parseInt(dl.getText());
            double b2=b1*(Integer.parseInt(dt.getText()));
            basico=(int)b2;}
            pst.setInt(6,basico);
            int hex=(a/(8*Integer.parseInt(dl.getText())))*Integer.parseInt(he.getText());
                pst.setInt(7, hex);
                 if("Gerente".equals(cr.getText())){
            ven.setText("0");
            }
                 int yvm=Integer.parseInt(ven.getText());
                 double vb=yvm*0.03;
            int comisiones=(int)vb;
           
       pst.setInt(8, comisiones);
       pst.setInt(9, Integer.parseInt(nh.getText()));
       
       pst.setInt(10, 88211);
       int dev=basico+Integer.parseInt(nh.getText())+hex+comisiones+88211;
       pst.setInt(11, dev);
       double con2=(dev-88211)*0.04;
       String con3=""+(int)con2;
       int salud=Integer.parseInt(con3);
       pst.setInt(12, salud);
       double con4=(dev-88211)*0.04;
       String con5=""+(int)con4;
       int pen=Integer.parseInt(con5);
       pst.setInt(13, pen);
       int apo=Integer.parseInt(af.getText());
       pst.setInt(14,apo);
       
       if(nn>0){
       dep=dev*10/100;}
       int sub=(dev-(Integer.parseInt(re.getText()))-(Integer.parseInt(sp.getText()))-salud-dep-(Integer.parseInt(apa.getText())));
       int exen=sub*25/100;
       int total=sub-exen;
       int uvt=total/33156;
       int uvt2=uvt-150;
       int uvt3=(uvt2*(28/100))+10;
     
       if(dev>3315600){
       reten=uvt3*33156;
       }
       pst.setInt(15, reten);
       int emb=Integer.parseInt(em.getText());
       pst.setInt(16, emb);
       int td=salud+pen+apo+reten+emb;
       pst.setInt(17, td);
       int suel=dev-td;
       pst.setInt(18, suel);
                    
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro exitoso");
            
        }  catch (SQLException ex) {
            Logger.getLogger(Nomina_Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Algunos campos con valores numericos tienen datos invalidos");
        }
          catch (NullPointerException ex ) {
             JOptionPane.showMessageDialog(null, "Algunos campos estan vacios");
        }
  
         
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NominaP a=new NominaP();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
        //minimizar ventana
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        //Cerrar
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        /*
        String natu1 = natura.getText();
        String v= valor.getText();
        int d=Integer.parseInt(v);

        if("Credito".equals(natu1)){
            c=c+d;
        }else if("Debito".equals(natu1)){
            b=b+d;
        }

        //Boton Agregar
        String tipo=natura.getText();

        String []Datos= new String[7];
        Datos[0]=dd.getText();

        Datos[1]=codigo.getText();

        Datos[2]=jTextField2.getText();

        Datos[3]=valor.getText();

        Datos[4]=natura.getText();

        Datos[5]=auxiliar.getText();

        Datos[6]=jTextField14.getText();

        modelo.addRow(Datos);

        if (tipo=="Credito"){

            Datos[0]=dd.getText();

            Datos[1]=codigo.getText();

            Datos[2]=jTextField2.getText();

            Datos[3]=valor.getText();

            Datos[4]=natura.getText();

            Datos[5]=(String) auxiliar.getText();

            Datos[6]=jTextField14.getText();

        }
        else if (tipo=="Debito"){
            Datos[0]=dd.getText();
            Datos[1]=codigo.getText();
            Datos[2]=jTextField2.getText();
            Datos[3]=valor.getText();
            Datos[4]=(String) natura.getText();
            Datos[5]=auxiliar.getText();
            Datos[6]=jTextField14.getText();

            modelo2.addRow(Datos);
        }else{

        }
        */
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        /*
        String natu1 = natura.getText();
        String v= valor.getText();
        int d=Integer.parseInt(v);
        String dia = Integer.toString(fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(fecha.getCalendar().get(Calendar.YEAR));
        String fech = (year + "-" + mes+ "-" + dia);
        dd.setText(fech);

        if("Credito".equals(natu1)){
            c=c+d;
        }else if("Debito".equals(natu1)){
            b=b+d;
        }

        //Boton Agregar
        String tipo=natura.getText();

        String []Datos= new String[7];
        Datos[0]=dd.getText();

        Datos[1]=codigo.getText();

        Datos[2]=jTextField2.getText();

        Datos[3]=valor.getText();

        Datos[4]=natura.getText();

        Datos[5]=auxiliar.getText();

        Datos[6]=jTextField14.getText();

        modelo.addRow(Datos);

        if (tipo=="Credito"){

            Datos[0]=dd.getText();

            Datos[1]=codigo.getText();

            Datos[2]=jTextField2.getText();

            Datos[3]=valor.getText();

            Datos[4]=natura.getText();

            Datos[5]=(String) auxiliar.getText();

            Datos[6]=jTextField14.getText();

        }
        else if (tipo=="Debito"){
            Datos[0]=dd.getText();
            Datos[1]=codigo.getText();
            Datos[2]=jTextField2.getText();
            Datos[3]=valor.getText();
            Datos[4]=(String) natura.getText();
            Datos[5]=auxiliar.getText();
            Datos[6]=jTextField14.getText();

            modelo2.addRow(Datos);
        }else{

        }
        */
    }//GEN-LAST:event_jPanel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nomina_Generar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nomina_Generar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nomina_Generar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nomina_Generar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nomina_Generar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField af;
    private javax.swing.JTextField ap;
    private javax.swing.JTextField apa;
    private javax.swing.JTextField ced;
    private javax.swing.JTextField cr;
    private javax.swing.JTextField dl;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField em;
    private javax.swing.JTextField he;
    private javax.swing.JTextField iv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nh;
    private javax.swing.JTextField re;
    private javax.swing.JTextField sp;
    private javax.swing.JTextField ven;
    // End of variables declaration//GEN-END:variables
}
